package de.nimzan.node.server.process;

import de.nimzan.node.config.NodeConfig;
import de.nimzan.node.server.GameServer;
import org.yaml.snakeyaml.DumperOptions;
import org.yaml.snakeyaml.Yaml;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Properties;

public class ServerProcessManager {

    public Process startGameServer(GameServer gameServer) throws IOException {

        writeServerProperties(gameServer);
        writeRegisterServerPluginConfig(gameServer);

        ProcessBuilder pb = new ProcessBuilder(
                "java", "-Xmx512M", "-jar", "server.jar", "nogui"
        );
        pb.directory(gameServer.getDirectory().toFile());

        return pb.start();
    }

    public boolean stopGameServer(GameServer gameServer) {
        Process process = gameServer.getProcess();
        process.destroy();

        try {
            process.waitFor();
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            return false;
        }

        return deleteDir(gameServer.getDirectory().toFile());
    }

    public boolean deleteDir(File file) {
        if (!file.exists()) {
            return true;
        }

        if(file.isDirectory()) {
            File[] files = file.listFiles();
            if(files != null) {
                for (File child : files) {
                    if(!deleteDir(child)) {
                        return false;
                    }
                }
            }
        }

        return file.delete();
    }

    private void writeServerProperties(GameServer gameServer) throws IOException {
        Path propertiesFile = gameServer.getDirectory().resolve("server.properties");

        Properties properties = new Properties();

        // Load existing properties if present
        if (Files.exists(propertiesFile)) {
            try (InputStream in = Files.newInputStream(propertiesFile)) {
                properties.load(in);
            }
        }

        // Set the port
        properties.setProperty("server-port", String.valueOf(gameServer.getPort()));

        try (OutputStream out = Files.newOutputStream(propertiesFile)) {
            properties.store(out, "Generated by NodeService");
        }
    }

    private void writeRegisterServerPluginConfig(GameServer gameServer) throws IOException {
        Path pluginDir = gameServer.getDirectory()
                .resolve("plugins")
                .resolve("RegisterServerPlugin");

        Files.createDirectories(pluginDir);

        Path configFile = pluginDir.resolve("config.yml");

        LinkedHashMap<String, Object> data = new LinkedHashMap<>();
        data.put("serverUid", gameServer.getUuid().toString());
        data.put("masterUrl", NodeConfig.masterUrl());

        DumperOptions opts = new DumperOptions();
        opts.setDefaultFlowStyle(DumperOptions.FlowStyle.BLOCK);
        opts.setPrettyFlow(true);
        opts.setIndent(2);

        Yaml yaml = new Yaml(opts);
        try (Writer writer = new OutputStreamWriter(Files.newOutputStream(configFile), StandardCharsets.UTF_8)){
            yaml.dump(data, writer);
        }
    }
}
